spring.application.name=hotel
spring.datasource.url=${mysql://root:ZEJuMazFYQFzZwiYfCBPLLMIcBEGCvRa@shuttle.proxy.rlwy.net:11390/railway}
spring.datasource.username=${Root}
spring.datasource.password=${ZEJuMazFYQFzZwiYfCBPLLMIcBEGCvRa}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update