spring.application.name=hotel
spring.datasource.url=${mysql://root:ZEJuMazFYQFzZwiYfCBPLLMIcBEGCvRa@shuttle.proxy.rlwy.net:11390/railway}
spring.datasource.username=${Root}
spring.datasource.password=${ZEJuMazFYQFzZwiYfCBPLLMIcBEGCvRa}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=nouseacc98@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true